server:
  port: 9001
spring:
  application:
    name: tensquare-base
  rabbitmq: #用于监听 云配置的修改情况
    host: 192.168.44.132
  datasource:
    driverClassName:
    url: jdbc:mysql://192.168.44.1313:3306/tensquare_base?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
eureka: # # eureka相当于Zookeeper 服务注册中心
  client:  #eureka 客户端 意思是要把此服(article)务注册到 eureka服务里面
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance: #跨域访问 方便测试...
    prefer-ip-address: true
