server: 
  port: 9004
spring: 
  application:  
    name: tensquare -article #指定服务名
  datasource:  
    driverClassName:
    url: jdbc:mysql://192.168.0.102:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.44.130  #默认端口号6379
  data:
    mongodb:
      host: 192.168.0.102 #use demo  创建数据库切换到demo数据库,要有数据才会显示在数据库列表中
      database: recruitdb #db.goods.insert({id:123,name:'hello'}) // 给goods表 插入数据(如果此表不存在则创建)
