server: 
  port: 9004
spring: 
  application:  
    name: tensquare -article #指定服务名
  datasource:  
    driverClassName:
    url: jdbc:mysql://192.168.44.131:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.44.131  #默认端口号6379
  data:
    mongodb:
      host: 192.168.44.131 #use demo  创建数据库切换到demo数据库,要有数据才会显示在数据库列表中
      database: recruitdb #db.goods.insert({id:123,name:'hello'}) // 给goods表 插入数据(如果此表不存在则创建)
eureka: # # eureka相当于Zookeeper 服务注册中心
  client:  #eureka 客户端 意思是要把此服(article)务注册到 eureka服务里面
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance: #跨域访问 方便测试...
    prefer-ip-address: true