server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName:
    url: jdbc:mysql://192.168.0.102:3306/tensquare_base?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true