server: 
  port: 9001
spring: 
  application:  
    name: tensquare -article #指定服务名
  datasource:  
    driverClassName:
    url: jdbc:mysql://192.168.44.130:3306/tensquare_article??charaterEncoding=utf-8e
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
